import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Factory, Globe2, Handshake, ShieldCheck } from "lucide-react";
import { metadata as makeMeta } from "@/lib/seo";

export const metadata = makeMeta("About OUKITEL New Energy | Global B2B Energy Partner","Meet OUKITEL New Energy, a portable power station manufacturer supporting global distributors, wholesalers and OEM/ODM brands.","/about");

const strengths = [[Factory,"Manufacturing foundation","Structured production, testing and delivery processes for portable energy products."],[Globe2,"Global market experience","Business experience across 60+ markets with channel-focused product support."],[Handshake,"B2B partnership","Wholesale, distributor and OEM/ODM cooperation built around long-term market development."],[ShieldCheck,"Quality accountability","Model-level specifications, inspection records and compliance documentation review."]] as const;

export default function Page(){return <main><section className="company-hero dark"><div className="container company-hero-grid"><div><h1 className="display">From China, Empowering Global Energy Businesses</h1><p className="lede">OUKITEL New Energy develops portable power stations and energy storage solutions for distributors, wholesalers, brands, solar channels and professional project partners.</p><div className="actions"><Link className="btn btn-primary" href="/#inquiry">Discuss Cooperation <ArrowRight size={18}/></Link><Link className="btn btn-outline" href="/factory">Explore Our Factory</Link></div></div><div className="brand-visual"><span>OUKITEL</span><Image src="/images/products/p2001e-plus.webp" alt="OUKITEL portable power station for global business partners" width={900} height={900} priority/></div></div></section><section className="section"><div className="container company-story"><div><span className="eyebrow">Company profile</span><h2 className="title">A Technology Brand with a Dedicated New Energy Business</h2></div><div><p className="body">OUKITEL was established as a technology brand in 2013. Its new energy business has focused on portable and expandable power solutions since 2019, combining product development, manufacturing coordination, global sales and partner support.</p><p className="body">Our goal is practical: help professional buyers source dependable LiFePO4 power products, build differentiated market offers and maintain clear communication from evaluation through mass delivery.</p></div></div></section><section className="section soft"><div className="container"><div className="section-heading"><div><span className="eyebrow">Why OUKITEL</span><h2 className="title">Built for Professional Energy Channels</h2></div><p className="body">We present verified products and cooperation capabilities clearly, without invented certifications, customers or project claims.</p></div><div className="about-strengths">{strengths.map(([Icon,title,text])=><article key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><section className="section"><div className="container about-numbers"><div><strong>2013</strong><span>OUKITEL brand established</span></div><div><strong>2019</strong><span>New energy business development</span></div><div><strong>60+</strong><span>Markets with business experience</span></div><div><strong>30,000+ m2</strong><span>Manufacturing footprint</span></div></div></section></main>}
