import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BatteryCharging, CheckCircle2, ClipboardCheck, PackageCheck, ScanLine, ShieldCheck } from "lucide-react";
import { LocationMap } from "@/components/LocationMap";
import { metadata as makeMeta } from "@/lib/seo";

export const metadata=makeMeta("Portable Power Station Factory & Quality Control | OUKITEL","Explore OUKITEL portable power station manufacturing, ATS testing, aging inspection, battery safety and final quality control in Huizhou, China.","/factory");
const controls=[[ClipboardCheck,"Incoming inspection","Key materials and components are checked before entering production."],[BatteryCharging,"Battery safety","LiFePO4 cells and BMS functions are reviewed against model requirements."],[ScanLine,"ATS test","Automatic transfer switching and electrical response are tested for backup applications."],[ShieldCheck,"Aging test","Finished units undergo controlled operation before shipment approval."],[CheckCircle2,"Final inspection","Appearance, output functions, accessories and documentation are checked."],[PackageCheck,"Packaging control","Packaging configuration and shipment readiness are verified by order."]] as const;

export default function Page(){return <main><section className="factory-hero dark"><div className="container factory-hero-grid"><div><h1 className="display">Portable Power Station Manufacturing You Can Evaluate</h1><p className="lede">OUKITEL combines production planning, battery and inverter verification, ATS testing, aging inspection, final inspection and product traceability for global B2B orders.</p><div className="actions"><Link className="btn btn-primary" href="/#inquiry">Request Factory Information <ArrowRight size={18}/></Link></div></div><div className="factory-visual"><div className="factory-logo">OUKITEL</div><Image src="/images/products/p5000e-pro.webp" alt="OUKITEL heavy-duty energy storage product manufactured for global markets" width={900} height={900} priority/><span>Huizhou Manufacturing &amp; Quality Center</span></div></div></section><section className="section"><div className="container"><div className="section-heading"><div><span className="eyebrow">Quality process</span><h2 className="title">Structured Checks from Components to Shipment</h2></div><p className="body">Testing scope and certification availability differ by product model and destination market. Documentation is confirmed during quotation and order review.</p></div><div className="factory-controls">{controls.map(([Icon,title,text],index)=><article key={title}><b>{String(index+1).padStart(2,"0")}</b><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><section className="section soft"><div className="container factory-capability"><div><span className="eyebrow">Production capability</span><h2 className="title">Supporting Wholesale and OEM/ODM Programs</h2><p className="body">The manufacturing organization supports model evaluation, production scheduling, inspection coordination, branded packaging and delivery preparation for qualified business partners.</p><ul><li>30,000+ m2 manufacturing footprint</li><li>Portable and expandable energy product platforms</li><li>Order-specific quality and documentation checkpoints</li><li>Batch and product traceability support</li></ul></div><div className="factory-product-wall"><Image src="/images/products/p1000e-plus-official.webp" alt="OUKITEL P1000E Plus product platform" width={700} height={540}/><Image src="/images/products/bp2000e-pro.webp" alt="OUKITEL BP2000E Pro expandable power system" width={700} height={700}/></div></div></section><section className="section"><div className="container"><span className="eyebrow">Factory location</span><h2 className="title">Visit Our Huizhou Manufacturing Site</h2><div className="single-location"><LocationMap title="OUKITEL Huizhou Factory" label="Manufacturing & Quality" address="4th Floor, Building 7, Hengang Technology Industrial Park, Huiyang District, Huizhou City, Guangdong Province, China" coordinates={{lat:22.79,lon:114.46}} bbox={[114.42,22.76,114.50,22.82]}/></div></div></section></main>}
