import type { FollowUpRecord, Market } from "./types";

export const markets: Market[] = [
  { country: "China", city: "Shenzhen", timeZone: "Asia/Shanghai", region: "China" },
  { country: "Germany", city: "Berlin", timeZone: "Europe/Berlin", region: "Europe" },
  { country: "France", city: "Paris", timeZone: "Europe/Paris", region: "Europe" },
  { country: "Spain", city: "Madrid", timeZone: "Europe/Madrid", region: "Europe" },
  { country: "Poland", city: "Warsaw", timeZone: "Europe/Warsaw", region: "Europe" },
  { country: "Italy", city: "Rome", timeZone: "Europe/Rome", region: "Europe" },
  { country: "Ukraine", city: "Kyiv", timeZone: "Europe/Kyiv", region: "Europe" },
  { country: "United Kingdom", city: "London", timeZone: "Europe/London", region: "Europe" },
  { country: "Netherlands", city: "Amsterdam", timeZone: "Europe/Amsterdam", region: "Europe" },
  { country: "Kuwait", city: "Kuwait City", timeZone: "Asia/Kuwait", region: "Middle East" },
  { country: "Saudi Arabia", city: "Riyadh", timeZone: "Asia/Riyadh", region: "Middle East" },
  { country: "United Arab Emirates", city: "Dubai", timeZone: "Asia/Dubai", region: "Middle East" },
  { country: "Qatar", city: "Doha", timeZone: "Asia/Qatar", region: "Middle East" },
  { country: "Oman", city: "Muscat", timeZone: "Asia/Muscat", region: "Middle East" },
  { country: "Bahrain", city: "Manama", timeZone: "Asia/Bahrain", region: "Middle East" },
  { country: "United States", city: "New York", timeZone: "America/New_York", region: "North America" },
  { country: "United States", city: "Los Angeles", timeZone: "America/Los_Angeles", region: "North America" },
  { country: "Puerto Rico", city: "San Juan", timeZone: "America/Puerto_Rico", region: "Caribbean" },
  { country: "Jamaica", city: "Kingston", timeZone: "America/Jamaica", region: "Caribbean" },
  { country: "Bahamas", city: "Nassau", timeZone: "America/Nassau", region: "Caribbean" },
  { country: "Dominican Republic", city: "Santo Domingo", timeZone: "America/Santo_Domingo", region: "Caribbean" },
  { country: "Colombia", city: "Bogota", timeZone: "America/Bogota", region: "Latin America" },
  { country: "Chile", city: "Santiago", timeZone: "America/Santiago", region: "Latin America" },
  { country: "Philippines", city: "Manila", timeZone: "Asia/Manila", region: "Southeast Asia" },
  { country: "Indonesia", city: "Jakarta", timeZone: "Asia/Jakarta", region: "Southeast Asia" },
  { country: "South Africa", city: "Johannesburg", timeZone: "Africa/Johannesburg", region: "Africa" },
  { country: "Nigeria", city: "Lagos", timeZone: "Africa/Lagos", region: "Africa" },
  { country: "Australia", city: "Sydney", timeZone: "Australia/Sydney", region: "Oceania" },
];

function record(id: number, data: Omit<FollowUpRecord, "id">): FollowUpRecord {
  return { id: `oukitel-${id}`, ...data };
}

export const initialFollowUps: FollowUpRecord[] = [
  record(1, {
    customerName: "US OEM Buyer",
    company: "4P Energy OEM Co.",
    country: "United States",
    city: "Los Angeles",
    region: "North America",
    timeZone: "America/Los_Angeles",
    email: "sample1@example.invalid",
    whatsapp: "Demo only",
    linkedin: "Demo profile",
    customerType: "OEM Brand",
    sourceChannel: "LinkedIn",
    productCategory: "Portable Power Station",
    interestedModel: "P2001E Pro",
    businessModel: "OEM Branding",
    targetMarket: "United States",
    estimatedQuantity: "500 pcs",
    plugType: "US",
    certificationRequirement: "FCC / UL",
    oemOdmRequirement: "Private label + packaging",
    lastContactDate: "2026-06-14",
    lastContactTime: "10:30",
    lastContactMethod: "Email",
    followUpContent: "Quotation shared and OEM requirements discussed.",
    customerReply: "Customer asked for better pricing and OEM quantity clarity.",
    currentStage: "Quotation Sent",
    replyStatus: "Need Price",
    leadTemperature: "Hot",
    followUpRhythm: "Every 2-3 Days",
    customerValueTier: "A",
    followUpSummary: "Quotation sent. Customer needs better target price and OEM quantity confirmation.",
    nextAction: "Follow up quotation",
    nextFollowUpDate: "2026-06-18",
    notes: "OEM price structure needed.",
    estimatedOrderValue: 180000,
    probability: 70,
    expectedCloseDate: "2026-07-20",
    paymentStatus: "Not Started",
    riskLevel: "Medium",
    mainBlocker: "Target price gap",
    needBossSupport: "Yes",
    needTeamSupport: "Pricing approval",
    forecastNotes: "OEM price structure needed.",
    annualPotential: "500K-1M USD",
    companyValue: "High",
    channelStrength: "Strong",
    lastYearSalesRevenue: "800K USD",
    annualSalesVolume: "500 units/year",
    mainSalesChannels: "OEM projects, offline dealer network",
    purchasePlan12Months: "500K-1M USD in 2026",
    firstOrderEstimate: "100 pcs P2001E Pro",
    decisionMakerConfirmed: "Yes",
    currentCompetitorSales: "EcoFlow, BLUETTI",
    oemReason: "Higher margin",
    whyWeCanWin: "Customer needs OEM branding and better margin.",
    whyWeMayLose: "Target price gap and competitor comparison.",
    paymentRisk: "Medium",
    riskControlPlan: "Deposit required; Boss approval required",
    bossDecisionNeeded: "Yes",
    bossDecisionNotes: "Special price approval and OEM approval",
    nextMilestone: "PI confirmation",
    milestoneDueDate: "2026-06-20",
    strategicCustomer: "Yes",
    seasonalDemandDriver: "Summer camping season",
    history: [{ id: "event-1", date: "2026-06-14", method: "Email", content: "Quotation and OEM request discussed.", reply: "Need Price" }],
    emailLogs: [{ sentDate: "2026-06-14", subject: "OUKITEL OEM quotation", summary: "Shared quotation and OEM options.", replySummary: "Need Price", replyStatus: "Need Price" }],
    customerGrade: "A - High Priority",
  }),
  record(2, {
    customerName: "German Retail Buyer",
    company: "DE Outdoor Chain",
    country: "Germany",
    city: "Berlin",
    region: "Europe",
    timeZone: "Europe/Berlin",
    email: "sample2@example.invalid",
    whatsapp: "Demo only",
    linkedin: "Demo profile",
    customerType: "Chain Store",
    sourceChannel: "Email",
    productCategory: "Portable Power Station",
    interestedModel: "P1000E Plus",
    businessModel: "Retail Chain Supply",
    targetMarket: "Germany",
    estimatedQuantity: "300 pcs",
    plugType: "EU",
    certificationRequirement: "CE / RoHS",
    oemOdmRequirement: "No",
    lastContactDate: "2026-06-12",
    lastContactTime: "10:30",
    lastContactMethod: "Email",
    followUpContent: "Catalog and assortment discussion.",
    customerReply: "Waiting for model selection.",
    currentStage: "Product Catalog Sent",
    replyStatus: "Need Catalog",
    leadTemperature: "Warm",
    followUpRhythm: "Monthly",
    customerValueTier: "A",
    followUpSummary: "Waiting for model selection and retail buying window.",
    nextAction: "Send product comparison",
    nextFollowUpDate: "2026-06-19",
    notes: "Outdoor retail chain comparison.",
    estimatedOrderValue: 95000,
    probability: 40,
    expectedCloseDate: "2026-08-01",
    paymentStatus: "Not Started",
    riskLevel: "Low",
    mainBlocker: "Model selection",
    needBossSupport: "No",
    needTeamSupport: "Catalog follow-up",
    forecastNotes: "Outdoor retail chain comparison.",
    annualPotential: "500K-1M USD",
    companyValue: "High",
    channelStrength: "Strong",
    lastYearSalesRevenue: "1M+ USD",
    annualSalesVolume: "1 container/quarter",
    mainSalesChannels: "Retail chain, online store",
    purchasePlan12Months: "First container in Q3",
    firstOrderEstimate: "300 pcs mixed models",
    decisionMakerConfirmed: "Yes",
    currentCompetitorSales: "Jackery, EcoFlow",
    oemReason: "Unknown",
    whyWeCanWin: "Strong retail demand for seasonal backup and outdoor models.",
    whyWeMayLose: "Model selection delay.",
    paymentRisk: "Low",
    riskControlPlan: "Deposit required",
    bossDecisionNeeded: "No",
    bossDecisionNotes: "",
    nextMilestone: "Model selection",
    milestoneDueDate: "2026-06-25",
    strategicCustomer: "Yes",
    seasonalDemandDriver: "Summer outdoor and winter backup demand",
    history: [{ id: "event-2", date: "2026-06-12", method: "Email", content: "Catalog and retail assortment shared.", reply: "Need Catalog" }],
    emailLogs: [{ sentDate: "2026-06-12", subject: "Portable power station assortment", summary: "Shared product catalog.", replySummary: "Need Catalog", replyStatus: "Need Catalog" }],
    customerGrade: "B - Medium Priority",
  }),
  record(3, {
    customerName: "Jamaica Dealer",
    company: "Kingston Power Dealer",
    country: "Jamaica",
    city: "Kingston",
    region: "Caribbean",
    timeZone: "America/Jamaica",
    email: "sample3@example.invalid",
    whatsapp: "Demo only",
    linkedin: "Demo profile",
    customerType: "Competitor Dealer",
    sourceChannel: "Website Inquiry",
    productCategory: "Solar Generator",
    interestedModel: "P1500E Plus",
    businessModel: "Regional Distributor",
    targetMarket: "Jamaica",
    estimatedQuantity: "120 pcs",
    plugType: "US",
    certificationRequirement: "Local import documents",
    oemOdmRequirement: "No",
    lastContactDate: "2026-06-10",
    lastContactTime: "10:30",
    lastContactMethod: "WhatsApp",
    followUpContent: "Discussed dealer margin and hurricane season stock.",
    customerReply: "Still reviewing competitor comparison.",
    currentStage: "Waiting Reply",
    replyStatus: "No Reply",
    leadTemperature: "Warm",
    followUpRhythm: "Weekly",
    customerValueTier: "B",
    followUpSummary: "Competitor dealer background. Need send margin comparison and hurricane season stock plan.",
    nextAction: "Send product comparison",
    nextFollowUpDate: "2026-06-18",
    notes: "Hurricane season backup opportunity.",
    estimatedOrderValue: 48000,
    probability: 30,
    expectedCloseDate: "2026-07-30",
    paymentStatus: "Not Started",
    riskLevel: "Medium",
    mainBlocker: "Competitor comparison",
    needBossSupport: "No",
    needTeamSupport: "Need market info",
    forecastNotes: "Hurricane season backup opportunity.",
    annualPotential: "100K-500K USD",
    companyValue: "Medium",
    channelStrength: "Medium",
    lastYearSalesRevenue: "Unknown",
    annualSalesVolume: "Unknown",
    mainSalesChannels: "Offline dealer network",
    purchasePlan12Months: "Pre-season stock if margin works",
    firstOrderEstimate: "80-120 pcs",
    decisionMakerConfirmed: "Unknown",
    currentCompetitorSales: "EcoFlow / BLUETTI",
    oemReason: "Competitor price too high",
    whyWeCanWin: "Margin opportunity and hurricane season demand.",
    whyWeMayLose: "Existing competitor relationship.",
    paymentRisk: "Medium",
    riskControlPlan: "Advance payment",
    bossDecisionNeeded: "No",
    bossDecisionNotes: "",
    nextMilestone: "Stock confirmation",
    milestoneDueDate: "2026-06-21",
    strategicCustomer: "No",
    seasonalDemandDriver: "Hurricane season",
    history: [{ id: "event-3", date: "2026-06-10", method: "WhatsApp", content: "Dealer margin and stock timing discussed.", reply: "No Reply" }],
    emailLogs: [{ sentDate: "2026-06-10", subject: "Dealer margin comparison", summary: "Shared dealer margin outline.", replySummary: "No Reply", replyStatus: "No Reply" }],
    customerGrade: "B - Medium Priority",
  }),
  record(4, {
    customerName: "Kuwait Distributor",
    company: "Gulf Energy Partner",
    country: "Kuwait",
    city: "Kuwait City",
    region: "Middle East",
    timeZone: "Asia/Kuwait",
    email: "sample4@example.invalid",
    whatsapp: "Demo only",
    linkedin: "Demo profile",
    customerType: "Distributor",
    sourceChannel: "WhatsApp",
    productCategory: "Portable Power Station",
    interestedModel: "P5000E Plus",
    businessModel: "Exclusive Agent",
    targetMarket: "Kuwait",
    estimatedQuantity: "200 pcs",
    plugType: "UK",
    certificationRequirement: "GCC documents",
    oemOdmRequirement: "No",
    lastContactDate: "2026-06-15",
    lastContactTime: "10:30",
    lastContactMethod: "Phone Call",
    followUpContent: "Exclusive distributor terms discussed.",
    customerReply: "Interested in exclusive scope and first order pricing.",
    currentStage: "Negotiation",
    replyStatus: "Interested",
    leadTemperature: "Hot",
    followUpRhythm: "Every 2-3 Days",
    customerValueTier: "A",
    followUpSummary: "Exclusive distributor discussion. Need confirm pricing structure, territory scope and first order plan.",
    nextAction: "Send distributor terms",
    nextFollowUpDate: "2026-06-18",
    notes: "Exclusive distributor discussion.",
    estimatedOrderValue: 160000,
    probability: 65,
    expectedCloseDate: "2026-07-18",
    paymentStatus: "Not Started",
    riskLevel: "Medium",
    mainBlocker: "Exclusive terms not confirmed",
    needBossSupport: "Yes",
    needTeamSupport: "Boss decision",
    forecastNotes: "Exclusive distributor discussion.",
    annualPotential: "500K-1M USD",
    companyValue: "High",
    channelStrength: "Strong",
    lastYearSalesRevenue: "1M+ USD",
    annualSalesVolume: "1 container/month",
    mainSalesChannels: "Wholesale, offline dealer network",
    purchasePlan12Months: "First order in Q3 with exclusivity review",
    firstOrderEstimate: "1 x 20ft container",
    decisionMakerConfirmed: "Yes",
    currentCompetitorSales: "Solar and backup power products",
    oemReason: "Distributor exclusivity",
    whyWeCanWin: "Direct factory support and stronger exclusivity proposal.",
    whyWeMayLose: "Regional conflict or exclusive term disagreement.",
    paymentRisk: "Medium",
    riskControlPlan: "Deposit required; Boss approval required",
    bossDecisionNeeded: "Yes",
    bossDecisionNotes: "Exclusive agency approval",
    nextMilestone: "Distributor terms confirmation",
    milestoneDueDate: "2026-06-22",
    strategicCustomer: "Yes",
    seasonalDemandDriver: "Summer backup power demand",
    history: [{ id: "event-4", date: "2026-06-15", method: "Phone Call", content: "Exclusive distributor terms discussed.", reply: "Interested" }],
    emailLogs: [{ sentDate: "2026-06-15", subject: "Exclusive distribution proposal", summary: "Discussed pricing structure and territory.", replySummary: "Interested", replyStatus: "Interested" }],
    customerGrade: "A - High Priority",
  }),
  record(5, {
    customerName: "Puerto Rico Buyer",
    company: "PR Emergency Supply",
    country: "Puerto Rico",
    city: "San Juan",
    region: "Caribbean",
    timeZone: "America/Puerto_Rico",
    email: "sample5@example.invalid",
    whatsapp: "Demo only",
    linkedin: "Demo profile",
    customerType: "Wholesaler",
    sourceChannel: "Xiaoman CRM",
    productCategory: "Solar Generator",
    interestedModel: "P2001E Plus",
    businessModel: "Government / Emergency Supply",
    targetMarket: "Puerto Rico",
    estimatedQuantity: "220 pcs",
    plugType: "US",
    certificationRequirement: "FCC",
    oemOdmRequirement: "No",
    lastContactDate: "2026-06-14",
    lastContactTime: "10:30",
    lastContactMethod: "Email",
    followUpContent: "Waiting deposit arrangement for emergency stock.",
    customerReply: "Needs updated payment plan.",
    currentStage: "Payment Pending",
    replyStatus: "Replied",
    leadTemperature: "Hot",
    followUpRhythm: "Every 2-3 Days",
    customerValueTier: "A",
    followUpSummary: "Waiting deposit arrangement. Customer is close to order but payment schedule needs confirmation.",
    nextAction: "Confirm payment plan",
    nextFollowUpDate: "2026-06-18",
    notes: "Waiting deposit arrangement.",
    estimatedOrderValue: 132000,
    probability: 80,
    expectedCloseDate: "2026-06-28",
    paymentStatus: "Waiting Deposit",
    riskLevel: "Medium",
    mainBlocker: "Payment schedule",
    needBossSupport: "Yes",
    needTeamSupport: "Finance follow-up",
    forecastNotes: "Waiting deposit arrangement.",
    annualPotential: "1M+ USD",
    companyValue: "High",
    channelStrength: "Strong",
    lastYearSalesRevenue: "Unknown",
    annualSalesVolume: "Emergency seasonal bulk orders",
    mainSalesChannels: "Government project, wholesale",
    purchasePlan12Months: "Hurricane season buying window",
    firstOrderEstimate: "220 pcs emergency stock",
    decisionMakerConfirmed: "Yes",
    currentCompetitorSales: "Unknown",
    oemReason: "Unknown",
    whyWeCanWin: "Urgent backup power demand and fast supply support.",
    whyWeMayLose: "Payment risk and approval timing.",
    paymentRisk: "High",
    riskControlPlan: "Advance payment; No credit terms; Boss approval required",
    bossDecisionNeeded: "Yes",
    bossDecisionNotes: "Payment risk decision",
    nextMilestone: "Payment plan confirmation",
    milestoneDueDate: "2026-06-19",
    strategicCustomer: "Yes",
    seasonalDemandDriver: "Hurricane season",
    history: [{ id: "event-5", date: "2026-06-14", method: "Email", content: "Payment arrangement under discussion.", reply: "Replied" }],
    emailLogs: [{ sentDate: "2026-06-14", subject: "Payment plan follow-up", summary: "Requested deposit confirmation.", replySummary: "Replied", replyStatus: "Replied" }],
    customerGrade: "A - High Priority",
  }),
  record(6, {
    customerName: "Saudi Factory Visitor",
    company: "Riyadh Project Supply",
    country: "Saudi Arabia",
    city: "Riyadh",
    region: "Middle East",
    timeZone: "Asia/Riyadh",
    email: "sample6@example.invalid",
    whatsapp: "Demo only",
    linkedin: "Demo profile",
    customerType: "EPC Contractor",
    sourceChannel: "Exhibition",
    productCategory: "High-power Energy Storage",
    interestedModel: "BP5000E Pro Max",
    businessModel: "Project Order",
    targetMarket: "Saudi Arabia",
    estimatedQuantity: "100 sets",
    plugType: "UK",
    certificationRequirement: "SASO",
    oemOdmRequirement: "No",
    lastContactDate: "2026-06-09",
    lastContactTime: "10:30",
    lastContactMethod: "Factory Visit",
    followUpContent: "Factory visit completed and quote priorities discussed.",
    customerReply: "Need selected models and payment plan review.",
    currentStage: "Factory Visit Done",
    replyStatus: "Need Price",
    leadTemperature: "Hot",
    followUpRhythm: "Every 2-3 Days",
    customerValueTier: "A",
    followUpSummary: "Factory visit completed. Need follow up selected models, project timing and payment plan.",
    nextAction: "Send quotation",
    nextFollowUpDate: "2026-06-18",
    notes: "Factory visit completed.",
    estimatedOrderValue: 310000,
    probability: 70,
    expectedCloseDate: "2026-07-10",
    paymentStatus: "Not Started",
    riskLevel: "Medium",
    mainBlocker: "Price not confirmed",
    needBossSupport: "Yes",
    needTeamSupport: "Final quotation",
    forecastNotes: "Factory visit completed.",
    annualPotential: "500K-1M USD",
    companyValue: "High",
    channelStrength: "Strong",
    lastYearSalesRevenue: "Unknown",
    annualSalesVolume: "Project-based procurement",
    mainSalesChannels: "EPC projects, wholesale",
    purchasePlan12Months: "Project order in Q3",
    firstOrderEstimate: "100 sets",
    decisionMakerConfirmed: "Yes",
    currentCompetitorSales: "Deye, diesel generators",
    oemReason: "Market positioning",
    whyWeCanWin: "Factory visit improved trust and direct support position.",
    whyWeMayLose: "Price gap and competitor technical comparison.",
    paymentRisk: "Medium",
    riskControlPlan: "Deposit required",
    bossDecisionNeeded: "Yes",
    bossDecisionNotes: "Special price approval",
    nextMilestone: "Price approval",
    milestoneDueDate: "2026-06-21",
    strategicCustomer: "Yes",
    seasonalDemandDriver: "Project season",
    history: [{ id: "event-6", date: "2026-06-09", method: "Factory Visit", content: "Factory tour and project discussion completed.", reply: "Need Price" }],
    emailLogs: [{ sentDate: "2026-06-09", subject: "Factory visit follow-up", summary: "Sent recap and next quotation steps.", replySummary: "Need Price", replyStatus: "Need Price" }],
    customerGrade: "A - High Priority",
  }),
  record(7, {
    customerName: "Dormant EU Customer",
    company: "Old Europe Channel",
    country: "Netherlands",
    city: "Amsterdam",
    region: "Europe",
    timeZone: "Europe/Amsterdam",
    email: "sample7@example.invalid",
    whatsapp: "Demo only",
    linkedin: "Demo profile",
    customerType: "Distributor",
    sourceChannel: "Email",
    productCategory: "Portable Power Station",
    interestedModel: "TBD",
    businessModel: "Regional Distributor",
    targetMarket: "Europe",
    estimatedQuantity: "TBD",
    plugType: "EU",
    certificationRequirement: "CE",
    oemOdmRequirement: "No",
    lastContactDate: "2026-05-12",
    lastContactTime: "10:30",
    lastContactMethod: "Email",
    followUpContent: "Reactivation candidate only.",
    customerReply: "No reply recorded.",
    currentStage: "Dormant",
    replyStatus: "No Reply",
    leadTemperature: "Cold",
    followUpRhythm: "Monthly",
    customerValueTier: "C",
    followUpSummary: "No recent reply. Suitable for monthly reactivation with product update.",
    nextAction: "Wait for reply",
    nextFollowUpDate: "2026-07-12",
    notes: "Dormant EU channel contact.",
    estimatedOrderValue: 18000,
    probability: 10,
    expectedCloseDate: "2026-09-30",
    paymentStatus: "Not Applicable",
    riskLevel: "Low",
    mainBlocker: "Waiting customer reply",
    needBossSupport: "No",
    needTeamSupport: "Reactivation message",
    forecastNotes: "Dormant EU channel contact.",
    annualPotential: "Unknown",
    companyValue: "Unknown",
    channelStrength: "Unknown",
    lastYearSalesRevenue: "Unknown",
    annualSalesVolume: "Unknown",
    mainSalesChannels: "",
    purchasePlan12Months: "",
    firstOrderEstimate: "",
    decisionMakerConfirmed: "Unknown",
    currentCompetitorSales: "",
    oemReason: "Unknown",
    whyWeCanWin: "Seasonal product updates may reopen interest.",
    whyWeMayLose: "Long silence and unclear demand.",
    paymentRisk: "Unknown",
    riskControlPlan: "",
    bossDecisionNeeded: "No",
    bossDecisionNotes: "",
    nextMilestone: "Other",
    milestoneDueDate: "",
    strategicCustomer: "No",
    seasonalDemandDriver: "Winter backup power",
    history: [{ id: "event-7", date: "2026-05-12", method: "Email", content: "Last reactivation email sent.", reply: "No Reply" }],
    emailLogs: [{ sentDate: "2026-05-12", subject: "Product update", summary: "Shared product update for reactivation.", replySummary: "No Reply", replyStatus: "No Reply" }],
    customerGrade: "C - Low Priority",
  }),
];

// Future integration points only: CSV/Excel import, Xiaoman CRM export import,
// Google Sheets import/export, Gmail/Outlook sync, Calendar reminders, WhatsApp
// direct links, CRM database, email open tracking, follow-up notifications and
// AI scoring. Do not scrape systems or store real credentials in this version.
