export type Product={slug:string;name:string;category:string;featured?:boolean;capacity:string;output:string;cycles:string;solar:string;charge:string;eps:string;voltage:string;weight:string;summary:string;applications:string[];page:number};
export const products:Product[]=[
{slug:"p800e",name:"P800E",category:"Portable Power Station",capacity:"512 Wh",output:"800 W",cycles:"4,000+",solar:"200 W",charge:"~1 hour",eps:"<10 ms",voltage:"200-240 V",weight:"6.2 kg",summary:"Compact LiFePO4 power for entry-level retail, emergency kits and outdoor channels.",applications:["Camping","Mobile work","Emergency backup"],page:12},
{slug:"p1000e-plus",name:"P1000E Plus",category:"Portable Power Station",featured:true,capacity:"1,024 Wh",output:"1,800 W",cycles:"4,000+",solar:"500 W",charge:"~1 hour",eps:"<10 ms",voltage:"200-240 V",weight:"12 kg",summary:"A high-velocity core model balancing capacity, power and portability for global distributors.",applications:["Home backup","RV","Outdoor retail"],page:16},
{slug:"p1500e-plus",name:"P1500E Plus",category:"Portable Power Station",capacity:"1,536 Wh",output:"1,800 W",cycles:"4,000+",solar:"500 W",charge:"~1.6 hours",eps:"<10 ms",voltage:"200-240 V",weight:"14.2 kg",summary:"Extended runtime for higher-value retail portfolios and longer off-grid use.",applications:["Home backup","Road trips","Professional use"],page:18},
{slug:"p2001e-plus",name:"P2001E Plus",category:"Portable Power Station",featured:true,capacity:"2,048 Wh",output:"2,400 W",cycles:"4,000+",solar:"800 W",charge:"~1.5 hours",eps:"2,000 W backup",voltage:"200-240 V",weight:"21.5 kg",summary:"The versatile 2 kWh flagship for home backup, RV and emergency power distribution.",applications:["Power outages","RV","Refrigerator backup"],page:22},
{slug:"p2001e-pro",name:"P2001E Pro",category:"Portable Power Station",featured:true,capacity:"2,048 Wh",output:"3,200 W",cycles:"4,000+",solar:"1,000 W",charge:"~1.5 hours",eps:"2,000 W backup",voltage:"200-240 V",weight:"21.5 kg",summary:"Higher AC output for demanding appliances, professional channels and backup projects.",applications:["High-load backup","Worksites","Emergency response"],page:24},
{slug:"bp2000e-pro",name:"BP2000E Pro",category:"Expandable Power Station",capacity:"2,048 Wh",output:"2,400 W",cycles:"4,000+",solar:"1,000 W",charge:"~1.4 hours",eps:"Expandable",voltage:"200-240 V",weight:"TBC",summary:"Expandable energy platform for distributors serving modular home and off-grid demand.",applications:["Expandable backup","Off-grid homes","Energy dealers"],page:32},
{slug:"p5000e-pro",name:"P5000E Pro",category:"High-Capacity Power Station",capacity:"5,120 Wh",output:"3,200 W",cycles:"4,000+",solar:"1,000 W",charge:"~2 hours",eps:"High-capacity backup",voltage:"200-240 V",weight:"TBC",summary:"Large-capacity backup for premium residential, emergency and professional channels.",applications:["Whole-home essentials","Emergency supply","Professional backup"],page:38},
{slug:"ep2500",name:"EP2500",category:"Balcony Energy Storage",capacity:"2,048 Wh",output:"2,500 W",cycles:"6,000+",solar:"TBC",charge:"Grid / solar",eps:"Grid-tied & off-grid",voltage:"EU market",weight:"TBC",summary:"Plug-and-play balcony solar storage with modular expansion up to 12.28 kWh.",applications:["Balcony solar","Residential storage","EU energy retail"],page:42},
];
export const faqs=[
{q:"Do you support OEM and private-label projects?",a:"Yes. OUKITEL supports product selection, branding, packaging, documentation and project-based customization. Final scope depends on model, quantity and certification market."},
{q:"What information is needed for a wholesale quotation?",a:"Please share your destination market, preferred model or power range, estimated quantity, use case and required delivery schedule."},
{q:"Which certifications are available?",a:"Certification coverage varies by model and market. CE, FCC, MSDS, UN38.3, UL and PSE documentation must be confirmed against the exact model before ordering."},
{q:"Can you support local inventory and after-sales service?",a:"OUKITEL operates global service resources and overseas inventory in selected markets. Availability is confirmed by region and cooperation plan."},
];
export const markets=["United States","Europe","Caribbean","South America","Middle East","Africa"];
